[package]
name = "auto_trans"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xmltree = "0.10.3"
regex = "1.5.5"
urlencoding = "2.1.0"
reqwest = { version = "0.11.10", features = ["blocking"] }